# Generated by Django 2.0.7 on 2018-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('u_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('u_pass', models.CharField(max_length=40)),
            ],
        ),
    ]
