# Generated by Django 3.0.6 on 2020-06-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeLittletest',
            fields=[
                ('m_key', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('o_id', models.CharField(max_length=4)),
                ('t_id', models.CharField(max_length=4)),
                ('u_id', models.CharField(max_length=20)),
            ],
        ),
    ]
