# Generated by Django 3.0.6 on 2020-07-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_makelittletest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompQuestion',
            fields=[
                ('cq_key', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('q_id1', models.CharField(max_length=9)),
                ('q_id2', models.CharField(max_length=9)),
            ],
        ),
    ]
