# Generated by Django 2.0.7 on 2018-10-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLicenseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_num', models.IntegerField()),
                ('adr_date', models.DateTimeField()),
                ('check', models.BooleanField(default=False)),
                ('o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Org')),
            ],
        ),
    ]
