# Generated by Django 2.0.7 on 2018-10-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_addlicenserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlicenserequest',
            name='check',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_enable',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_hidden',
            field=models.IntegerField(default=0),
        ),
    ]
