# Generated by Django 2.0.7 on 2018-10-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20181018_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlicenserequest',
            name='check',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_admin',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_enable',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_hidden',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
