# Generated by Django 3.0.6 on 2020-07-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_questionpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_content',
            field=models.TextField(default=''),
        ),
    ]
