# Generated by Django 3.0.6 on 2020-07-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_questionjs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionjs',
            name='id',
        ),
        migrations.AlterField(
            model_name='questionjs',
            name='q_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
