# Generated by Django 2.0.7 on 2018-11-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20181018_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Org')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.LittleTest')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='u_admin',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_enable',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_hidden',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerimage',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.User'),
        ),
    ]
