# Generated by Django 2.0.7 on 2018-11-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20181108_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerimage',
            name='image',
            field=models.CharField(max_length=20),
        ),
    ]
