# Generated by Django 3.0.6 on 2020-08-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20200731_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentKeyWord',
            fields=[
                ('k_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('k_num', models.CharField(max_length=3)),
                ('k_keyword', models.CharField(max_length=20)),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question')),
            ],
        ),
    ]
