# Generated by Django 3.0.6 on 2020-10-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_contentkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCbtPm',
            fields=[
                ('q_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('q_test', models.CharField(max_length=2)),
                ('q_period', models.CharField(max_length=5)),
                ('q_q', models.CharField(max_length=2)),
                ('q_question', models.CharField(max_length=2)),
                ('q_symbol', models.CharField(max_length=1)),
                ('q_answer', models.CharField(max_length=1)),
                ('q_lastanswer', models.CharField(blank=True, max_length=1)),
                ('q_remarks', models.CharField(blank=True, max_length=1)),
                ('q_allocation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResultTestTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=4)),
                ('t_num', models.CharField(max_length=4)),
                ('r_answer', models.CharField(max_length=1)),
                ('r_date', models.DateTimeField()),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.User')),
            ],
        ),
    ]
