# Generated by Django 2.0.7 on 2018-11-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20181108_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerimage',
            name='o',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='answerimage',
            name='t',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='answerimage',
            name='u',
            field=models.CharField(max_length=20),
        ),
    ]
