# Generated by Django 3.0.6 on 2020-10-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_questioncbtpm_resulttesttemp'),
    ]

    operations = [

        migrations.CreateModel(
            name='QuestionCbtPmResult',
            fields=[
                ('r_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('q_test', models.CharField(max_length=2)),
                ('q_period', models.CharField(max_length=5)),
                ('o_id', models.CharField(max_length=4)),
                ('t_id', models.CharField(max_length=4)),
                ('u_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCbtPmResultDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=10)),
                ('q_test', models.CharField(max_length=2)),
                ('q_period', models.CharField(max_length=5)),
                ('q_q', models.CharField(max_length=2)),
                ('q_question', models.CharField(max_length=2)),
                ('q_symbol', models.CharField(max_length=1)),
                ('u_answer', models.CharField(max_length=1)),
            ],
        ),
    ]
