# Generated by Django 3.0.6 on 2020-10-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_questioncbtpm_questioncbtpmresult_questioncbtpmresultdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncbtpmresult',
            name='t_id',
        ),
    ]
