# Generated by Django 3.0.6 on 2020-10-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_remove_questioncbtpmresult_t_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncbtpmresultdetail',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
