# Generated by Django 3.0.6 on 2020-10-27 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_questioncbtpmresultdetail_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncbtpmresult',
            name='a_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
