# Generated by Django 3.0.6 on 2020-10-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_questionboki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionboki',
            name='b_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
