# Generated by Django 3.0.6 on 2020-10-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20201029_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionboki',
            name='b_field',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
