# Generated by Django 3.0.6 on 2020-11-05 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20201029_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncbtpmresult',
            name='b_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
