# Generated by Django 3.0.6 on 2020-11-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_questioncbtpmresult_b_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionboki',
            name='b_ocr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionboki',
            name='b_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
