# Generated by Django 3.0.6 on 2020-11-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_auto_20201106_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionboki',
            name='b_ocr',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
