# Generated by Django 3.0.6 on 2020-11-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20201106_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionboki',
            name='b_ocr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
