# Generated by Django 3.0.6 on 2020-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_auto_20201106_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBokiQ1AllowField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_field', models.CharField(max_length=40)),
                ('b_allow_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
