# Generated by Django 3.0.6 on 2020-11-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_questionbokiq1allowfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionboki',
            name='b_ans_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionboki',
            name='b_as_page',
            field=models.IntegerField(default=1),
        ),
    ]
