# Generated by Django 3.0.6 on 2020-11-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_auto_20201107_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionboki',
            name='b_com_page',
            field=models.IntegerField(default=0),
        ),
    ]
