# Generated by Django 3.0.6 on 2020-11-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_questionboki_b_com_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCbtAmResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=10)),
                ('q_id', models.CharField(max_length=9)),
                ('u_id', models.CharField(max_length=20)),
                ('o_id', models.CharField(max_length=4)),
                ('u_answer', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
