# Generated by Django 3.0.6 on 2020-12-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_questioncbtamresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionboki',
            name='b_field2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='questionboki',
            name='b_field3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
