# Generated by Django 3.0.6 on 2020-12-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_auto_20201209_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionIp',
            fields=[
                ('ip_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ip_period', models.CharField(max_length=5)),
                ('ip_num', models.IntegerField(default=1)),
                ('ip_content', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_l_field', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_m_field', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_s_field', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
