# Generated by Django 3.0.6 on 2020-12-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0027_questionip'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionip',
            name='ip_answer',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
